<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DRT.Application\DRT.Application.csproj" />
    <ProjectReference Include="..\DRT.Domain\DRT.Domain.csproj" />
    <ProjectReference Include="..\DRT.Workflow\DRT.Workflow.csproj" />
  </ItemGroup>
</Project>
